name: Hello
on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
    tags:
      - 'v*'
      - 'release-*'
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
    - run : echo "RAJ SONI"
